### ISSUE TITLE
Halaman Admin

### ISSUE THREAD

**Issue by incursio13** [ulaai/rk-b#1]
Terdapat beberapa hal yang mungkin perlu diperbaiki: 

- Tampilan home pada halaman admin masih terlalu polos, mungkin dapat diberi diganti atau dihapus
- Tidak ada tombol logout untuk user

Sekian, terima kasih

**Comment by ivaldyp** [comment]
baik, masukan tersebut akan segera kami benarkan

**Comment by ivaldyp** [comment]
Tombol logout untuk user telah ditambahkan, mohon dicek. Terima kasih.

**Comment by incursio13** [comment]
tombol logout belum berfungsi ya ?

**Comment by ivaldyp** [comment]
untuk tombol sign out sudah dapat berfungsi sekarang, mohon dicek. Terima kasih

**Comment by ivaldyp** [comment]
Karena issue ini sudah selesai, maka akan kami tutup. Terima kasih.
