### ISSUE TITLE
mencoba daftar dengan data yang berbeda tetapi memberikan akun yang sama

### ISSUE THREAD

**Issue by panagua** [ulaai/rk-b#11]
saya mencoba mendaftarkan akun dengan data yang berbeda,(nrp,nama,nohp,dll),akan tetapi akun memberikan hasil daftar akun yang sama:Fathihah Ulya,5114100076

**Comment by ulaai** [comment]
Iya mas, karena kemarin kan dibilangnya tidak perlu pakai backend, jadi untuk saat ini apapun inputannya keluarannya masih sama. :))

**Comment by ulaai** [comment]
Halo, issue ini kami anggap sudah selesai, jadi kami tutup ya. Terima kasih :)
