### ISSUE TITLE
Fungsi icon/button

### ISSUE THREAD

**Issue by MHendriF** [ulaai/rk-b#12]
Untuk icon / button ini fungsinya apa ya?
![2017-05-22_13h17_59](https://cloud.githubusercontent.com/assets/24228896/26294900/28e01d7a-3ef1-11e7-9f41-42eadfc574b1.png)

**Comment by ivaldyp** [comment]
button tersebut sebenarnya tidak ada fungsinya, terimakasih untuk sudah mengingatkan, sudah kami hapus. Terima kasih.

**Comment by ivaldyp** [comment]
Karena issue ini sudah selesai, maka akan kami tutup. Terima kasih.
