### ISSUE TITLE
Fitur yang belum ada

### ISSUE THREAD

**Issue by MHendriF** [ulaai/rk-b#13]
Untuk fitur yang belum ada, yaitu :

- Lihat Schedule Pemakaian

- Download Proposal

- Fasilitas Setiap Ruangan

Silahkan ditambahkan, terimakasih.

**Comment by ulaai** [comment]
Untuk schedule pemakaian dan download proposal sudah ditambahkan, silakan dicek.

Untuk fasilitas setiap ruangan, kira-kira nanti inginnya dapat diakses di halaman mana ya? Apakah ditambah di sidebar atau mungkin hanya bisa dilihat saat ingin melakukan reservasi? Terima kasih.

**Comment by MHendriF** [comment]
ditambah halaman index saja, supaya setiap orang bisa lihat tanpa harus membuat akun terlebih dahulu.

**Comment by faishal15** [comment]
berarti maksudnya di halaman paling depan sebelum pengguna login?

**Comment by ulaai** [comment]
Untuk fasilitasnya sudah ditambahkan, silakan dicek

**Comment by MHendriF** [comment]
font sizenya di perbesar lagi ya

**Comment by faishal15** [comment]
Sudah dilakukan perbaikan terhadap font sizenya, silahkan dicek apakah sudah sesuai atau belum, terima kasih

**Comment by ulaai** [comment]
Halo, karena masalahnya sudah selesai jadi issue ini kami tutup, terima kasih
