### ISSUE TITLE
apakah kegunaan tombol ini untuk refresh saja?

### ISSUE THREAD

**Issue by panagua** [ulaai/rk-b#14]
apakah kegunaan tombol ini? untuk refresh kah? ketika saya klik hanya refresh page
![test](https://cloud.githubusercontent.com/assets/14936513/26341638/fc128660-3fbe-11e7-825c-62638fcb3cd9.PNG)

**Comment by panagua** [comment]
kalau untuk refresh saja menurut saya lebih baik dihilangkan

**Comment by faishal15** [comment]
sebenarnya bukan untuk refresh, tapi lebih kepada untuk kembali ke default halaman awal seperti halnya ikon di situs youtube.com yang jika diklik ikon youtubenya maka akan menuju ke halaman awal youtube.

**Comment by faishal15** [comment]
Karena issue ini sudah selesai, maka kami tutup, terima kasih
