### ISSUE TITLE
Font Fasilitas

### ISSUE THREAD

**Issue by MHendriF** [ulaai/rk-b#15]
Untuk font size pada fasilitas setiap ruangan agar diperbesar sehingga dapat di baca dengan jelas

**Comment by faishal15** [comment]
Sudah dilakukan perbaikan, coba diupdate lagi dan dilihat apa sudah sesuai atau belum, terima kasih.

**Comment by ulaai** [comment]
Halo, karena masalahnya sudah selesai jadi issue ini kami tutup, terima kasih
