### ISSUE TITLE
Alur Peminjaman Ruangan

### ISSUE THREAD

**Issue by MHendriF** [ulaai/rk-b#16]
Mohon ditambahkan fitur alur peminjaman ruangan. Bentuknya bisa berupa deskripsi atau ilustrasi.
Fitur ini terlatak pada halaman utama seperti fasilitas ruangan, terimakasih.

**Comment by ulaai** [comment]
Halo, fitur alur peminjaman ruangan sudah ditambahkan ya, silakan dicek :)

**Comment by MHendriF** [comment]
Ok sudah saya cek

**Comment by ulaai** [comment]
Halo, karena masalahnya sudah selesai jadi issue ini kami tutup, terima kasih :)
