### ISSUE TITLE
Form peminjaman ruaangan

### ISSUE THREAD

**Issue by incursio13** [ulaai/rk-b#2]
Terdapat beberapa hal yang mungkin perlu diperbaiki:

- Field ruangan peminjaman sebaiknya dibuat inputan drop down dan multiple select
- Field tanggal mulai dan tanggal selesai sebaiknya ditampilkan seperti kalender dan secara otomatis menunjukkan rentang waktu

sekian dan terimakasih

**Comment by faishal15** [comment]
Perbaikan terkait poin 1 dan 2 sudah dilakukan, silahkan dicek, terima kasih.

**Comment by faishal15** [comment]
Dikarenakan issue ini sudah selesai, terima kasih dan kami tutup
