### ISSUE TITLE
Halaman index/index.html

### ISSUE THREAD

**Issue by incursio13** [ulaai/rk-b#3]
![capture](https://cloud.githubusercontent.com/assets/16316048/25988822/b78e3136-3723-11e7-9447-7383b9160159.JPG)
untuk halaman diatas pada bagian sebelah kanan terdapat tabel, itu menunjukkan apa ya ?
mohon diberikan keterangan
terimakasih.

**Comment by ulaai** [comment]
Halo, mohon maaf karena halaman yang ini selanjutnya sudah tidak dipakai lagi. Terima kasih atas tanggapannya. :)
