### ISSUE TITLE
Halaman Daftar Akun

### ISSUE THREAD

**Issue by MHendriF** [ulaai/rk-b#5]
Untuk nama halamannya sendiri mohon untuk diubah
![2017-05-13_05h20_27](https://cloud.githubusercontent.com/assets/24228896/26018890/ed810a20-379b-11e7-8e2a-d2aa5901b7ae.png)

**Comment by faishal15** [comment]
Sudah dilakukan perbaikan, mohon untuk dicek, terima kasih

**Comment by faishal15** [comment]
Karena issue ini sudah selesai, maka kami tutup, terima kasih
