### ISSUE TITLE
Login dan Register

### ISSUE THREAD

**Issue by MHendriF** [ulaai/rk-b#6]
Untuk fungsi login dan registernya masih belum jalan, jika diklik tidak menghasilkan respon apapun. Terimakasih

**Comment by faishal15** [comment]
Sudah dilakukan perbaikan terhadap dua hal tersebut, silahkan dicek kembali, terima kasih

**Comment by faishal15** [comment]
Karena issue ini sudah selesai, maka kami tutup, terima kasih
