### ISSUE TITLE
Link Belum Sinkron

### ISSUE THREAD

**Issue by MHendriF** [ulaai/rk-b#7]
Terdapat beberapa link yang belum sinkron jika kita buka dari halaman reservasi. Terimakasih

**Comment by faishal15** [comment]
Bisakah dideskripsikan lebih jelas apa saja link yang tidak sinkron tersebut? terima kasih

**Comment by incursio13** [comment]
pada bagian navbar
semisal memilih menu reservasi dan akan kembali ke menu home linknya belum mengarah ke home, dan terdapat beberapa link di navbar yang masih error

**Comment by MHendriF** [comment]
sepertinya di masing-masing view link nya belum sama, silahkan bisa dicek. Terimakasih.

**Comment by ivaldyp** [comment]
- Untuk link yang tadinya arahnya belum benar atau masih error, arahnya sudah dibenarkan.
- Untuk masing-masing view yang link nya belum sama, link nya sudah dibenarkan.

Mohon di periksa kembali dan terima kasih atas masukannya

**Comment by incursio13** [comment]
masih terdapat link yang belum terhubung 
sebagai contoh dari menu reservasi, jika ingin memilih menu status atau menu proses selesai maka akan diarahkan ke link yang salah
![image](https://cloud.githubusercontent.com/assets/16316048/26285678/a316505a-3e7e-11e7-9d3c-e4427da17dd7.png)

**Comment by incursio13** [comment]
masih terdapat kesalahan link 
![image](https://cloud.githubusercontent.com/assets/16316048/26286002/1223f438-3e85-11e7-880a-5c9382df0b00.png)
jika menu "proses selesai" diklik 2 dst kali akan menghasilkan tampilan yang berbeda 
terimakasih.

**Comment by ivaldyp** [comment]
baik, masalah "proses selesai" akan segera kami benarkan

**Comment by ivaldyp** [comment]
Untuk menu "proses selesai" telah dibenarkan agar tidak menghasilkan tampilan yang berbeda. 
Terima kasih.

**Comment by ivaldyp** [comment]
karena issue ini sudah selesai, maka akan kami tutup. Terima kasih.
