### ISSUE TITLE
Tabel Reservasi

### ISSUE THREAD

**Issue by MHendriF** [ulaai/rk-b#8]
Untuk tabel reservasi nama tabelnya bisa diganti menjadi Daftar / List reservasi dan ukuran tabelnya difullkan saja supaya terlihat lebih bagus
![2017-05-13_05h38_35](https://cloud.githubusercontent.com/assets/24228896/26019365/0d705aae-379f-11e7-826b-3fd75134898a.png)

**Comment by faishal15** [comment]
Sudah dilakukan perbaikan, silahkan di cek, terima kasih

**Comment by faishal15** [comment]
Karena issue ini sudah selesai, maka issue ini kami tutup, terima kasih
