### ISSUE TITLE
Header yang sama

### ISSUE THREAD

**Issue by MHendriF** [ulaai/rk-b#9]
Untuk header di masing-masing halamannya masih sama. Silahkan diperbaiki terimakasih.

**Comment by ivaldyp** [comment]
maaf, tapi header yang dimaksud itu yang bagaimana ya? terima kasih

**Comment by incursio13** [comment]
mungkin ini yang dimaksud @leopard28 
![image](https://cloud.githubusercontent.com/assets/16316048/26312608/56df91a6-3f32-11e7-9cc8-7b15d0345f09.png)
![image](https://cloud.githubusercontent.com/assets/16316048/26312625/66c2674c-3f32-11e7-9747-c0345839eeac.png)

**Comment by ivaldyp** [comment]
untuk header pada masing-masing halaman sudah diperbaiki, mohon dicek kembali. Terima kasih

**Comment by ivaldyp** [comment]
Karena issue ini sudah selesai, maka akan kami tutup. Terima kasih.

**Comment by ivaldyp** [comment]
Karena issue ini sudah selesai, maka akan kami tutup. Terima kasih.
